const keyboard = [
  { index: 1, key: "`", shift: "~" },
  { index: 2, key: "1", shift: "!" },
  { index: 3, key: "2", shift: "@" },
  { index: 4, key: "3", shift: "#" },
  { index: 5, key: "4", shift: "$" },
  { index: 6, key: "5", shift: "%" },
  { index: 7, key: "6", shift: "^" },
  { index: 8, key: "7", shift: "&" },
  { index: 9, key: "8", shift: "*" },
  { index: 10, key: "9", shift: "(" },
  { index: 11, key: "0", shift: ")" },
  { index: 12, key: "-", shift: "_" },
  { index: 13, key: "=", shift: "+" },
  { index: 14, key: "Tab" },
  { index: 15, key: "q", hangul: "ㅂ" },
  { index: 16, key: "w", hangul: "ㅈ" },
  { index: 17, key: "e", hangul: "ㄷ" },
  { index: 18, key: "r", hangul: "ㄱ" },
  { index: 19, key: "t", hangul: "ㅅ" },
  { index: 20, key: "y", hangul: "ㅛ" },
  { index: 21, key: "u", hangul: "ㅕ" },
  { index: 22, key: "i", hangul: "ㅑ" },
  { index: 23, key: "o", hangul: "ㅐ" },
  { index: 24, key: "p", hangul: "ㅔ" },
  { index: 25, key: "a", hangul: "ㅁ" },
  { index: 26, key: "s", hangul: "ㄴ" },
  { index: 27, key: "d", hangul: "ㅇ" },
  { index: 28, key: "f", hangul: "ㄹ" },
  { index: 29, key: "g", hangul: "ㅎ" },
  { index: 30, key: "h", hangul: "ㅗ" },
  { index: 31, key: "j", hangul: "ㅓ" },
  { index: 32, key: "k", hangul: "ㅏ" },
  { index: 33, key: "l", hangul: "ㅣ" },
  { index: 34, key: "z", hangul: "ㅋ" },
  { index: 35, key: "x", hangul: "ㅌ" },
  { index: 36, key: "c", hangul: "ㅊ" },
  { index: 37, key: "v", hangul: "ㅍ" },
  { index: 38, key: "b", hangul: "ㅠ" },
  { index: 39, key: "n", hangul: "ㅜ" },
  { index: 40, key: "m", hangul: "ㅡ" },
  { index: 41, key: "Q", hangul: "ㅃ" },
  { index: 42, key: "W", hangul: "ㅉ" },
  { index: 43, key: "E", hangul: "ㄸ" },
  { index: 44, key: "R", hangul: "ㄲ" },
  { index: 45, key: "T", hangul: "ㅆ" },
  { index: 46, key: "O", hangul: "ㅒ" },
  { index: 47, key: "P", hangul: "ㅖ" },
  { index: 48, key: "Backspace" },
  { index: 49, key: "Shift" },
  { index: 50, key: "Enter" },
  { index: 51, key: "Ctrl" },
  { index: 52, key: "Alt" },
  { index: 53, key: "Space" },
];

export default keyboard;
