const keyboard = [
  { lowerCase: "q", upperCase: "Q", hangul: "ㅂ", hangulCap: "ㅃ" },
  { lowerCase: "w", upperCase: "W", hangul: "ㅈ", hangulCap: "ㅉ" },
  { lowerCase: "e", upperCase: "E", hangul: "ㄷ", hangulCap: "ㄸ" },
  { lowerCase: "r", upperCase: "R", hangul: "ㄱ", hangulCap: "ㄲ" },
  { lowerCase: "t", upperCase: "T", hangul: "ㅅ", hangulCap: "ㅆ" },
  { lowerCase: "y", upperCase: "Y", hangul: "ㅛ" },
  { lowerCase: "u", upperCase: "U", hangul: "ㅕ" },
  { lowerCase: "i", upperCase: "I", hangul: "ㅑ" },
  { lowerCase: "o", upperCase: "O", hangul: "ㅐ", hangulCap: "ㅒ" },
  { lowerCase: "p", upperCase: "P", hangul: "ㅔ", hangulCap: "ㅖ" },
  { lowerCase: "a", upperCase: "A", hangul: "ㅁ" },
  { lowerCase: "s", upperCase: "S", hangul: "ㄴ" },
  { lowerCase: "d", upperCase: "D", hangul: "ㅇ" },
  { lowerCase: "f", upperCase: "F", hangul: "ㄹ" },
  { lowerCase: "g", upperCase: "G", hangul: "ㅎ" },
  { lowerCase: "h", upperCase: "H", hangul: "ㅗ" },
  { lowerCase: "j", upperCase: "J", hangul: "ㅓ" },
  { lowerCase: "k", upperCase: "K", hangul: "ㅏ" },
  { lowerCase: "l", upperCase: "L", hangul: "ㅣ" },
  { key: "FORMATTING" },
  { lowerCase: "z", upperCase: "Z", hangul: "ㅋ" },
  { lowerCase: "x", upperCase: "X", hangul: "ㅌ" },
  { lowerCase: "c", upperCase: "C", hangul: "ㅊ" },
  { lowerCase: "v", upperCase: "V", hangul: "ㅍ" },
  { lowerCase: "b", upperCase: "B", hangul: "ㅠ" },
  { lowerCase: "n", upperCase: "N", hangul: "ㅜ" },
  { lowerCase: "m", upperCase: "M", hangul: "ㅡ" },
  { key: "FORMATTING" },
  { key: "FORMATTING" },
  { key: "FORMATTING" },
];

export default keyboard;
