const keyboard = [
  { key: "q", hangul: "ㅂ" },
  { key: "w", hangul: "ㅈ" },
  { key: "e", hangul: "ㄷ" },
  { key: "r", hangul: "ㄱ" },
  { key: "t", hangul: "ㅅ" },
  { key: "y", hangul: "ㅛ" },
  { key: "u", hangul: "ㅕ" },
  { key: "i", hangul: "ㅑ" },
  { key: "o", hangul: "ㅐ" },
  { key: "p", hangul: "ㅔ" },
  { key: "a", hangul: "ㅁ" },
  { key: "s", hangul: "ㄴ" },
  { key: "d", hangul: "ㅇ" },
  { key: "f", hangul: "ㄹ" },
  { key: "g", hangul: "ㅎ" },
  { key: "h", hangul: "ㅗ" },
  { key: "j", hangul: "ㅓ" },
  { key: "k", hangul: "ㅏ" },
  { key: "l", hangul: "ㅣ" },
  { key: "z", hangul: "ㅋ" },
  { key: "x", hangul: "ㅌ" },
  { key: "c", hangul: "ㅊ" },
  { key: "v", hangul: "ㅍ" },
  { key: "b", hangul: "ㅠ" },
  { key: "n", hangul: "ㅜ" },
  { key: "m", hangul: "ㅡ" },
  { key: "Q", hangul: "ㅃ" },
  { key: "W", hangul: "ㅉ" },
  { key: "E", hangul: "ㄸ" },
  { key: "R", hangul: "ㄲ" },
  { key: "T", hangul: "ㅆ" },
  { key: "O", hangul: "ㅒ" },
  { key: "P", hangul: "ㅖ" },
];

export default keyboard;
